import pywhatkit

# Send a WhatsApp Message to a Contact at 1:30 PM

pywhatkit.sendwhatmsg("+919390332884", 
					"hey 1 this side Srujana!....Automatic message generated by python code", 
					8, 37)
 
