import pywhatkit

# Send a WhatsApp Message to a Contact at 6:05 PM

pywhatkit.sendwhatmsg("+917353438319", 
					"hey 1 this side Manasa!....Automatic message generated by python code", 
					18, 21)
