import pywhatkit

# Send a WhatsApp Message to a Contact at 1:30 PM

pywhatkit.sendwhatmsg("+9900433516", 
					"hey 1 this side Priyanka sp!....Automatic message generated by python code", 
                        16, 45)