# Importing the required modules
import pyautogui as pg
import time

# Delay to switch to WhatsApp Web
print("Program will run after 5 seconds...")
time.sleep(5)
print("Running...")

# Message to send
message = "Hi, This is an automatic random message generated by Python."

# Send message
pg.write(message)
pg.press("enter")
print("Message sent successfully!")
Hi, This is an automatic random message generated by Python.


