import pywhatkit

# Send a WhatsApp Message to a Contact at 11:30 PM

pywhatkit.sendwhatmsg("+916360483422", 
					"hey 1 this side Aliya!....Automatic message generated by python code", 
					15, 47)
 