import pywhatkit

# Send a WhatsApp Message to a Contact at 1:30 PM

pywhatkit.sendwhatmsg("+919900108012", 
					"hey 1 this side Siddiq!....Automatic message generated by python code", 
					15, 47)
 
