import pywhatkit

# Send a WhatsApp Message to a Contact at 8:00 AM

pywhatkit.sendwhatmsg("+916361158067", 
					"hello there skanda here!....Automatic message generated by python code", 
					8, 20)