import pywhatkit

# Send a WhatsApp Message to a Contact at 8:00 AM

pywhatkit.sendwhatmsg("+917019079045", 
					"hello there  sushil here!....Automatic message generated by python code", 
					8, 20)