import pywhatkit

# Send a WhatsApp Message to a Contact at 1:30 PM

pywhatkit.sendwhatmsg("+917406556771", 
					"hey 1 this side zaina!....Automatic message generated by python code", 
					15, 47)
 