import pywhatkit

# Send a WhatsApp Message to a Contact at 1:30 PM

pywhatkit.sendwhatmsg("+918431604744", 
					"hey 1 this side Nidhi!....Automatic message generated by python code", 
					19, 57)
 
