import pywhatkit

# Send a WhatsApp Message to a Contact at 1:30 PM

pywhatkit.sendwhatmsg("+919010390235", 
					"hey 1 this side Mustafa!....Automatic message generated by python code", 
					15, 47)
 