import pywhatkit

# Send a WhatsApp Message to a Contact at 1:30 PM

pywhatkit.sendwhatmsg("+918919293891", 
					"hey 1 this side vaishnavi....Automatic message generated by python code", 
					9, 15)
 
