import pyautogui as pg
import time

print("program will run after 5 second")
time.sleep(5)
print("running")Hi, This is automatic random message generated by python


# For loop
for i in range(1):
    # writing the messages
    pg.write("Hi, This is automatic random message generated by python")
    time.sleep(0.5) 
    # Seding the messages by pressing enter
    pg.press("Enter")
