import pywhatkit

# Send a WhatsApp Message to a Contact at 8:00 AM

pywhatkit.sendwhatmsg("+919972170225", 
					"hello there shreya here!....Automatic message generated by python code", 
					8, 20)