import pywhatkit

# Send a WhatsApp Message to a Contact at 1:30 PM

pywhatkit.sendwhatmsg("+919738999884", 
					"hey 1 this side Navya.G!....Automatic message generated by python code", 
					15, 47)
 