import pyautogui as pg
import time

# Delay to let you open WhatsApp Web and select a chat
print("Switch to WhatsApp Web. Program starts in 5 seconds...")
time.sleep(5)
print("Sending messages...")

# Number of messages to send
num_messages = 5

# Message to send
message = "Hi, This is an automatic random message generated by Python."

# Sending messages
for i in range(num_messages):
    print(f"Sending ({i+1}/{num_messages}): {message}")
    pg.write(message)
    pg.press("enter")
    time.sleep(1)
