import pywhatkit

# Send a WhatsApp Message to a Contact at 1:30 PM

pywhatkit.sendwhatmsg("+91 91484 87205", 
					"Hey, this side Haasini!...Automatic message generated by python code", 
					23, 42)
 