

import pywhatkit

# Send a WhatsApp Message to a Contact at 1:30 PM

pywhatkit.sendwhatmsg("+91842521579", 
					"hey 1 this side bali !....Automatic message generated by python code", 
					16, 55)
 
