import turtle

screen = turtle.Screen()
screen.title("Click to Draw Smileys")
pen = turtle.Turtle()
pen.hideturtle()
pen.speed(0)

def draw_smiley(x, y):
    pen.up()
    pen.goto(x, y - 50)
    pen.down()
    pen.fillcolor("yellow")
    pen.begin_fill()
    pen.circle(50)
    pen.end_fill()
    pen.up()
    for ex, ey in ((-15, 20), (15, 20)):
        pen.goto(x + ex, y + ey)
        pen.down()
        pen.fillcolor("white")
        pen.begin_fill()
        pen.circle(8)
        pen.end_fill()
        pen.up()
        pen.goto(x + ex, y + ey + 3)
        pen.down()
        pen.fillcolor("black")
        pen.begin_fill()
        pen.circle(3)
        pen.end_fill()
        pen.up()
    pen.goto(x - 25, y)
    pen.setheading(-60)
    pen.width(3)
    pen.down()
    pen.circle(30, 120)
    pen.up()
    pen.width(1)

screen.onclick(draw_smiley)
screen.listen()
turtle.done()
