import pywhatkit

# Send a WhatsApp Message to a Contact at 1:30 PM

pywhatkit.sendwhatmsg("+8105685675", 
					"hey 1 this side gowri!....Automatic message generated by python code", 
					15, 47)