import pywhatkit # type: ignore

# Send a WhatsApp Message to a Contact at 1:30 PM

pywhatkit.sendwhatmsg("+918431604744", 
					"hey 1 this side Gokul!....Automatic message generated by python code", 
					20, 7)
 
