import pywhatkit

# Send a WhatsApp Message to a Contact at 1:30 PM

pywhatkit.sendwhatmsg("+918187533710", 
					"hey 1 this side Nidhi!....Automatic message generated by python code", 
					15, 47)
 