import pywhatkit

# Send a WhatsApp Message to a Contact at 1:30 PM

pywhatkit.sendwhatmsg("+919740279202", 
					"hey 1 this side Abhijith Skanda HN!....Automatic message generated by python code", 
					15, 28)
 
