import pywhatkit

# Send a WhatsApp Message to a Contact at 1:30 PM

pywhatkit.sendwhatmsg("+913216549870", 
					"hey 1 this side Priyanka!....Automatic message generated by python code", 
					15, 47)
