import turtle
turtle.bgcolor("lightyellow")
pen = turtle.Turtle()
pen.speed(0)
pen.color("hotpink")
pen.pensize(2)
pen.penup()
pen.goto(0, -100)
pen.pendown()
for i in range(6):
    pen.circle(100, 60)
    pen.left(120)
    pen.circle(100, 60)
    pen.left(60)
pen.right(90)
pen.color("green")
pen.pensize(6)
pen.forward(300)
pen.backward(150)
pen.left(45)
pen.pensize(1)
pen.begin_fill()
pen.circle(50, 90)
pen.left(90)
pen.circle(50, 90)
pen.end_fill()
pen.hideturtle()
turtle.done()
