import pywhatkit

# Send a WhatsApp Message to a Contact at 1:30 PM

pywhatkit.sendwhatmsg("+63640385620", 
					"hey 1 this side shravya!....Automatic message generated by python code", 
					15, 47)
 
