import pywhatkit

# Send a WhatsApp Message to a Contact at 1:30 PM

pywhatkit.sendwhatmsg("+917406428649", 
					"hey 1 this side Praveen!....Automatic message generated by python code", 
					19, 53)
 
